# yaml-language-server: $schema=../gitlab2prov/config/schema.json
- extract:
        url: ["https://gitlab.com/example/foo"]
        token: tokenFoo
- extract:
        url: ["https://gitlab.com/example/bar"]
        token: tokenBar
- load:
        input: [example.rdf]
- pseudonymize:
- combine:
- save:
        output: combined
        format: [json, rdf, xml, dot]
- stats:
        fine: true
        explain: true
        formatter: table