# yaml-language-server: $schema=../gitlab2prov/config/schema.json
- extract:
        url: ["https://gitlab.com/example/foo"]
        token: tokenFoo
- extract:
        url: ["https://gitlab.com/example/bar"]
        token: tokenBar
- read:
        input: [example.rdf]
- combine:
- transform:
        use_pseudonyms: true
        remove_duplicates: true
- write:
        output: combined
        format: [json, rdf, xml, dot]
- stats:
        fine: true
        explain: true
        formatter: table