name: mypy-check

on: [push]

jobs:
  check:
    name: mypy-check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Mypy Check
      uses: jpetrucciani/mypy-check@0.761
      with:
      # File or directory to run mypy on
        path: gitlab2prov.py
